[package]
authors = ["Sebastian Rousseau <sebastian.rousseau@gmail.com>}"]
categories = ['development-tools', 'code-generation']
description = "A Rust library generator that helps create high-quality Rust libraries quickly and easily."
edition = "2021"
keywords = [
    'scaffolding',
    'library',
    'generator',
    'code-generation',
    'project-creation',
]
license = "MIT OR Apache-2.0"
name = "libmake"
repository = "https://github.com/sebastienrousseau/libmake.git"
rust-version = "1.66.1"
version = "0.0.1"
include = [
    "../../LICENSE-APACHE",
    "../../LICENSE-MIT",
    "/benches/**",
    "/build.rs",
    "/Cargo.toml",
    "/examples/**",
    "/README.md",
    "/src/**",
    "/tests/**",
]

# [[bench]]
# name = "benchmark"
# harness = false
# path = "benches/bench.rs"

[profile.bench]
debug = true

[dependencies]
clap = "4.1.6"
csv = "1.2.0"
figlet-rs = "0.1.5"
log = "0.4.17"
prettytable-rs = "0.10.0"
serde = { version = "1.0.152", features = ["derive"] }
simplelog = "0.12.0"


[dev-dependencies]
criterion = "0.4.0"

[lib]
crate-type = ["lib"]
name = "libmake"
path = "src/lib.rs"

[features]
default = []

[package.metadata.docs.rs]
all-features = true

[profile.dev]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
opt-level = 0
overflow-checks = true
panic = 'unwind'
rpath = false
strip = false

[profile.release]
codegen-units = 1        # Compile crates one after another so the compiler can optimize better
debug = false            # Disable debug information
debug-assertions = false # Disable debug assertions
incremental = false      # Disable incremental compilation
lto = true               # Enables link to optimizations
opt-level = "s"          # Optimize for binary size
overflow-checks = false  # Disable overflow checks
panic = "abort"          # Strip expensive panic clean-up logic
rpath = false            # Disable rpath
strip = "symbols"        # Automatically strip symbols from the binary.

[profile.test]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
opt-level = 0
overflow-checks = true
rpath = false
strip = false
