name: 🧪 Lint
on:
  push:
    branches:
      - feat/libmake
  pull_request:
    branches:
      - feat/libmake
  release:
    types: [created]

jobs:
  all:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          components: clippy
      - uses: actions/checkout@master
      - name: Check lints
        run: cargo clippy --workspace --all-features --all-targets --no-deps -- -D warnings
